[build]
  command = "npm run build"
  publish = "dist"

# Redirect all requests to index.html for SPA routing (important for React + Telegram redirect)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: add custom headers (for security or to avoid issues)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://*.telegram.org"
    X-Frame-Options = "ALLOW-FROM https://telegram.org"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
